<?php


$caterings = [
    [
        'id' => 1,
        'name' => 'FeastCrafters',
        'description' => 'Crafting unforgettable culinary experiences, FeastCrafters delivers customized buffet spreads for every event, combining creativity with diverse flavors to impress your guests.',
        'background_image' => './photoss/catering1.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Pakistan',
        'stars' => 5,
        'date' => '4d',
        'price' => 500,
        'services' => [
            'Full-service catering',
            'Customized menus',
            'On-site chefs',
            'Event planning',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Buffet Bliss',
        'description' => 'Catering offers vibrant, globally inspired dishes, blending traditional flavors with modern flair for unforgettable events.',
        'background_image' => './photoss/catering2.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => '⭐⭐⭐⭐⭐',
        'stars' => 5,
        'date' => '+',
        'price' => 750,
        'services' => [
            'International cuisine',
            'Vegan and vegetarian options',
            'Beverage services',
            'Decor and setup',
        ],
    ],
    [
        'id' => 3,
        'name' => 'The Grand Spread',
        'description' => 'For those who seek grandeur in every bite, The Grand Spread offers luxurious, all-encompassing buffet options that provide an opulent dining experience for any event.',
        'background_image' => './photoss/catering3.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'USA',
        'stars' => 4,
        'date' => '2d',
        'price' => 600,
        'services' => [
            'Gourmet appetizers',
            'Wine pairing',
            'Live cooking stations',
            'Elegant plating',
        ],
    ],
    [
        'id' => 4,
        'name' => 'Savory Sensations',
        'description' => ' Specializes in bringing delectable dishes to large gatherings, offering a variety of food choices that promise to satisfy and delight every guest.',
        'background_image' => './photoss/catering4.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Canada',
        'stars' => 5,
        'date' => '1w',
        'price' => 800,
        'services' => [
            'Buffet style service',
            'Themed menus',
            'Dessert bar',
            'Customizable packages',
        ],
    ],
    [
        'id' => 5,
        'name' => 'Gourmet Gala',
        'description' => 'Delivers a premium buffet experience with top-tier cuisine and impeccable service, ensuring that your event stands out with gourmet flavors and an elegant presentation.',
        'background_image' => './photoss/catering5.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'UK',
        'stars' => 3,
        'date' => '3d',
        'price' => 400,
        'services' => [
            'Event coordination',
            'High-end cuisine',
            'Private chefs',
            'Exclusive venues',
        ],
    ],
    [
        'id' => 6,
        'name' => 'Tasty Treats',
        'description' => 'Serves up indulgence with beautifully presented dishes and an expansive buffet selection, tailored to create a memorable dining experience for weddings and high-end events.',
        'background_image' => './photoss/catering6.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Australia',
        'stars' => 4,
        'date' => '5d',
        'price' => 350,
        'services' => [
            'Budget-friendly packages',
            'Casual dining',
            'Quick service',
            'Comfort food',
        ],
    ],
];
?>
