<?php


$caterings = [
    [
        'id' => 1,
        'name' => 'Blossom Avenue',
        'description' => 'A vibrant garden offering handpicked, fresh flowers for every occasion, from celebrations to heartfelt moments, with beauty in every stem.',
        'background_image' => './photos/flower1.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Pakistan',
        'stars' => 5,
        'date' => '',
        'price' => 500,
        'services' => [
            'Full-service catering',
            'Customized menus',
            'On-site chefs',
            'Event planning',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Petal & Bloom',
        'description' => 'Elegant floral creations that capture the essence of love, joy, and elegance, thoughtfully crafted to add charm to any event or space',
        'background_image' => './photos/flower2.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => '⭐⭐⭐⭐⭐',
        'stars' => 5,
        'date' => '',
        'price' => 750,
        'services' => [
            'International cuisine',
            'Vegan and vegetarian options',
            'Beverage services',
            'Decor and setup',
        ],
    ],
    [
        'id' => 3,
        'name' => 'Floral Symphony',
        'description' => 'Floral arrangements as harmonious as nature itself, bringing together a symphony of colors and fragrances to make your moments unforgettable.',
        'background_image' => './photos/flower3.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'USA',
        'stars' => 4,
        'date' => '',
        'price' => 600,
        'services' => [
            'Gourmet appetizers',
            'Wine pairing',
            'Live cooking stations',
            'Elegant plating',
        ],
    ],
    [
        'id' => 4,
        'name' => 'Blooming Wishes',
        'description' => 'Transforming your heartfelt wishes into beautifully crafted floral masterpieces, perfect for expressing emotions and creating lasting memories',
        'background_image' => './photos/flower4.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Canada',
        'stars' => 5,
        'date' => '',
        'price' => 800,
        'services' => [
            'Buffet style service',
            'Themed menus',
            'Dessert bar',
            'Customizable packages',
        ],
    ],
    [
        'id' => 5,
        'name' => 'Garden Grace',
        'description' => 'Gracefully designed bouquets and arrangements that bring natural beauty and timeless elegance to your home, office, or special events',
        'background_image' => './photos/flower5.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'UK',
        'stars' => 3,
        'date' => '',
        'price' => 400,
        'services' => [
            'Event coordination',
            'High-end cuisine',
            'Private chefs',
            'Exclusive venues',
        ],
    ],
    [
        'id' => 6,
        'name' => 'The Flower Palette',
        'description' => 'A colorful collection of nature’s finest blooms, arranged with artistic precision to brighten up your life and elevate every occasion.',
        'background_image' => './photos/flower6.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Australia',
        'stars' => 4,
        'date' => '',
        'price' => 350,
        'services' => [
            'Budget-friendly packages',
            'Casual dining',
            'Quick service',
            'Comfort food',
        ],
    ],
];
?>
