<?php


$caterings = [
    [
        'id' => 1,
        'name' => 'Flavor Haven Catering',
        'description' => 'Exquisite flavors for every occasion.',
        'background_image' => './photoss/catering1.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Pakistan',
        'stars' => 5,
        'date' => '4d',
        'price' => 500,
        'services' => [
            'Full-service catering',
            'Customized menus',
            'On-site chefs',
            'Event planning',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Slice & Delight Catering',
        'description' => 'Spice and Delight Catering offers vibrant, globally inspired dishes, blending traditional flavors with modern flair for unforgettable events.',
        'background_image' => './photoss/catering2.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => '⭐⭐⭐⭐⭐',
        'stars' => 5,
        'date' => '+',
        'price' => 750,
        'services' => [
            'International cuisine',
            'Vegan and vegetarian options',
            'Beverage services',
            'Decor and setup',
        ],
    ],
    [
        'id' => 3,
        'name' => 'Elegant Eats',
        'description' => 'Sophisticated cuisine for your elegant events.',
        'background_image' => './photoss/catering3.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'USA',
        'stars' => 4,
        'date' => '2d',
        'price' => 600,
        'services' => [
            'Gourmet appetizers',
            'Wine pairing',
            'Live cooking stations',
            'Elegant plating',
        ],
    ],
    [
        'id' => 4,
        'name' => 'Savory Sensations',
        'description' => 'Delicious and savory dishes to delight your guests.',
        'background_image' => './photoss/catering4.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Canada',
        'stars' => 5,
        'date' => '1w',
        'price' => 800,
        'services' => [
            'Buffet style service',
            'Themed menus',
            'Dessert bar',
            'Customizable packages',
        ],
    ],
    [
        'id' => 5,
        'name' => 'Gourmet Gala',
        'description' => 'Premium catering services for grand celebrations.',
        'background_image' => './photoss/catering5.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'UK',
        'stars' => 3,
        'date' => '3d',
        'price' => 400,
        'services' => [
            'Event coordination',
            'High-end cuisine',
            'Private chefs',
            'Exclusive venues',
        ],
    ],
    [
        'id' => 6,
        'name' => 'Tasty Treats',
        'description' => 'Affordable and tasty options for all your needs.',
        'background_image' => './photoss/catering6.jpeg',
        'user_image' => './photoss/call.jpg',
        'location' => 'Australia',
        'stars' => 4,
        'date' => '5d',
        'price' => 350,
        'services' => [
            'Budget-friendly packages',
            'Casual dining',
            'Quick service',
            'Comfort food',
        ],
    ],
];
?>
