<?php


$caterings = [
    [
        'id' => 1,
        'name' => 'Melody Lane',
        'description' => 'A haven for music lovers, offering a wide selection of instruments and accessories to help you create beautiful melodies, from beginners to professionals',
        'background_image' => './photos/flower1.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Pakistan',
        'stars' => 5,
        'date' => '',
        'price' => 500,
        'services' => [
            'Full-service catering',
            'Customized menus',
            'On-site chefs',
            'Event planning',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Harmonic Vibes',
        'description' => 'Your one-stop shop for instruments, equipment, and expert advice, providing everything you need to bring harmony to your music.',
        'background_image' => './photos/flower2.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => '⭐⭐⭐⭐⭐',
        'stars' => 5,
        'date' => '',
        'price' => 750,
        'services' => [
            'International cuisine',
            'Vegan and vegetarian options',
            'Beverage services',
            'Decor and setup',
        ],
    ],
    [
        'id' => 3,
        'name' => 'Rhythm & Strings',
        'description' => 'A store dedicated to all things strings and percussion, helping musicians find the perfect rhythm and tone for their sound journey.',
        'background_image' => './photos/flower3.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'USA',
        'stars' => 4,
        'date' => '',
        'price' => 600,
        'services' => [
            'Gourmet appetizers',
            'Wine pairing',
            'Live cooking stations',
            'Elegant plating',
        ],
    ],
    [
        'id' => 4,
        'name' => 'SoundScape Studios',
        'description' => 'Explore a world of music with premium instruments and audio gear, designed for musicians who want to create their own unique soundscapes.',
        'background_image' => './photos/flower4.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Canada',
        'stars' => 5,
        'date' => '',
        'price' => 800,
        'services' => [
            'Buffet style service',
            'Themed menus',
            'Dessert bar',
            'Customizable packages',
        ],
    ],
    [
        'id' => 5,
        'name' => 'TuneCraft Music',
        'description' => 'Crafting the perfect tune is easier with our range of high-quality instruments and gear, curated for musicians at every stage of their journey',
        'background_image' => './photos/flower5.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'UK',
        'stars' => 3,
        'date' => '',
        'price' => 400,
        'services' => [
            'Event coordination',
            'High-end cuisine',
            'Private chefs',
            'Exclusive venues',
        ],
    ],
    [
        'id' => 6,
        'name' => 'The Music Nest',
        'description' => 'A cozy spot for musicians to discover instruments, sheet music, and expert advice, offering a nurturing environment for musical growth.',
        'background_image' => './photos/flower6.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Australia',
        'stars' => 4,
        'date' => '',
        'price' => 350,
        'services' => [
            'Budget-friendly packages',
            'Casual dining',
            'Quick service',
            'Comfort food',
        ],
    ],
];
?>
