<?php


$caterings = [
    [
        'id' => 1,
        'name' => 'Eternal Elegance',
        'description' => 'A sophisticated and timeless venue that exudes class and luxury, perfect for hosting weddings, formal events, and elegant celebrations with a touch of grandeur.',
        'background_image' => './photos/flower1.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Pakistan',
        'stars' => 5,
        'date' => '',
        'price' => 500,
        'services' => [
            'Full-service catering',
            'Customized menus',
            'On-site chefs',
            'Event planning',
        ],
    ],
    [
        'id' => 2,
        'name' => 'Luxe Horizons',
        'description' => 'A stunning venue with panoramic views, perfect for weddings, galas, and corporate events, combining style and sophistication for any occasion.',
        'background_image' => './photos/flower2.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => '⭐⭐⭐⭐⭐',
        'stars' => 5,
        'date' => '',
        'price' => 750,
        'services' => [
            'International cuisine',
            'Vegan and vegetarian options',
            'Beverage services',
            'Decor and setup',
        ],
    ],
    [
        'id' => 3,
        'name' => 'The Crystal Garden',
        'description' => 'An enchanting, nature-inspired venue with lush surroundings and sparkling interiors, ideal for romantic weddings and serene gatherings.',
        'background_image' => './photos/flower3.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'USA',
        'stars' => 4,
        'date' => '',
        'price' => 600,
        'services' => [
            'Gourmet appetizers',
            'Wine pairing',
            'Live cooking stations',
            'Elegant plating',
        ],
    ],
    [
        'id' => 4,
        'name' => 'Celestial Hall',
        'description' => 'A versatile and modern venue, with celestial-inspired décor and spacious layouts, perfect for hosting everything from parties to conferences.',
        'background_image' => './photos/flower4.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Canada',
        'stars' => 5,
        'date' => '',
        'price' => 800,
        'services' => [
            'Buffet style service',
            'Themed menus',
            'Dessert bar',
            'Customizable packages',
        ],
    ],
    [
        'id' => 5,
        'name' => 'Timeless Retreat',
        'description' => 'A venue that blends classic architecture with modern amenities, creating a timeless setting for both intimate and large-scale events.',
        'background_image' => './photos/flower5.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'UK',
        'stars' => 3,
        'date' => '',
        'price' => 400,
        'services' => [
            'Event coordination',
            'High-end cuisine',
            'Private chefs',
            'Exclusive venues',
        ],
    ],
    [
        'id' => 6,
        'name' => 'The Pinnacle Pavilion',
        'description' => 'A premier venue known for its sleek design and impeccable service, offering a perfect backdrop for high-end events and memorable celebrations.',
        'background_image' => './photos/flower6.jpeg',
        'user_image' => './photos/call.jpg',
        'location' => 'Australia',
        'stars' => 4,
        'date' => '',
        'price' => 350,
        'services' => [
            'Budget-friendly packages',
            'Casual dining',
            'Quick service',
            'Comfort food',
        ],
    ],
];
?>
